#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
load_versions

cmd="${1:-build}"

case "$cmd" in
  build)
    if toolbox_exists && [[ -f "$STATE_DIR/tools.built" ]] \
       && [[ "$STATE_DIR/tools.built" -nt "$ROOT/tools/Dockerfile" ]] \
       && [[ "$STATE_DIR/tools.built" -nt "$ROOT/VERSIONS" ]]; then
      info "toolbox up to date"
      exit 0
    fi
    step "Building toolbox image (first run takes a few minutes)"
    docker build \
      --build-arg "KUBECTL_VERSION=$KUBECTL_VERSION" \
      --build-arg "KIND_VERSION=$KIND_VERSION" \
      --build-arg "KUSTOMIZE_VERSION=$KUSTOMIZE_VERSION" \
      --build-arg "HELM_VERSION=$HELM_VERSION" \
      --build-arg "K9S_VERSION=$K9S_VERSION" \
      --build-arg "KFP_SDK_VERSION=$KFP_SDK_VERSION" \
      -t "$TOOLBOX_IMAGE" "$ROOT/tools"
    touch "$STATE_DIR/tools.built"
    ok "toolbox built"
    ;;

  shell)
    require_toolbox
    info "you are in the toolbox. kubectl/kustomize/kind/helm/k9s/kfp are on PATH."
    tb_tty bash
    ;;

  freeze)
    # Record what the toolbox actually resolved to, so teammates get the same.
    require_toolbox
    step "Freezing resolved tool versions into VERSIONS.lock"
    {
      echo "# Generated by 'make freeze' on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      echo "# Commit this file. It is what makes the lab reproducible."
      echo "KUSTOMIZE_VERSION=$(tb kustomize version 2>/dev/null | tr -d 'v\r' | awk '{print $1}')"
      echo "HELM_VERSION=$(tb helm version --short 2>/dev/null | cut -d+ -f1 | tr -d '\r')"
      echo "K9S_VERSION=$(tb k9s version --short 2>/dev/null | awk '/Version/{print $2}' | tr -d '\r')"
      echo "KFP_SDK_VERSION=$(tb python3 -c 'import kfp;print(kfp.__version__)' 2>/dev/null | tr -d '\r')"
    } > "$ROOT/VERSIONS.lock"
    cat "$ROOT/VERSIONS.lock"
    ok "wrote VERSIONS.lock"
    ;;

  *)
    die "unknown: $cmd (build|shell|freeze)"
    ;;
esac
